#!/bin/bash

# Generate secrets
DEEZER_API_TRACK_QUERY_URL=process.env.DEEZER_API_TRACK_QUERY_URL
# SPOTIFY_API_TOKEN_GENERATOR_URL=process.env.SPOTIFY_API_TOKEN_GENERATOR_URL
# SPOTIFY_CLIENT_ID=process.env.SPOTIFY_CLIENT_ID
# SPOTIFY_API_TRACK_QUERY_URL=process.env.SPOTIFY_API_TRACK_QUERY_URL
# SPOTIFY_CLIENT_SECRET=process.env.SPOTIFY_CLIENT_SECRET


# Add secrets to repository settings
echo "Adding secrets to repository settings..."
echo "::add-secret::DEEZER_API_TRACK_QUERY_URL=$DEEZER_API_TRACK_QUERY_URL"
# echo "::add-secret::SPOTIFY_API_TOKEN_GENERATOR_URL=$SPOTIFY_API_TOKEN_GENERATOR_URL"
# echo "::add-secret::SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID"
# echo "::add-secret::SPOTIFY_API_TRACK_QUERY_URL=$SPOTIFY_API_TRACK_QUERY_URL"
# echo "::add-secret::SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET"