#!/bin/bash

# Generate secrets
# DEEZER_API_TRACK_QUERY_URL=$DEEZER_API_TRACK_QUERY_URL
SPOTIFY_API_TOKEN_GENERATOR_URL=$SPOTIFY_API_TOKEN_GENERATOR_URL
SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID
SPOTIFY_API_TRACK_QUERY_URL=$SPOTIFY_API_TRACK_QUERY_URL
SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET

# Add secrets to repository settings
echo "Adding secrets to repository settings..."
echo "DEEZER_API_TRACK_QUERY_URL=$DEEZER_API_TRACK_QUERY_URL" >> $GITHUB_ENV
echo "SPOTIFY_API_TOKEN_GENERATOR_URL=$SPOTIFY_API_TOKEN_GENERATOR_URL" >> $GITHUB_ENV
echo "SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID" >> $GITHUB_ENV
echo "SPOTIFY_API_TRACK_QUERY_URL=$SPOTIFY_API_TRACK_QUERY_URL" >> $GITHUB_ENV
echo "SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET" >> $GITHUB_ENV