name: Unit Tests

on: [push, pull_request]

jobs:
  build-and-test:
    name: Testing the modules and their functions
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 19.x
      uses: actions/setup-node@v2
      with:
        node-version: 19.x

    - name: Install dependencies
      run: npm install

    - name: Set environment variables
      run: |
        echo "DEEZER_API_TRACK_QUERY_URL=${{ secrets.DEEZER_API_TRACK_QUERY_URL }}" >> .env

    - name: Run tests
      run: |
        echo $DEEZER_API_TRACK_QUERY_URL  # just to check if the env variable is set

