---
name: Super-Linter

on: [push, pull_request]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install StandardJS
        run: npm install standard@latest --save-dev --save-exact

      - name: Attempt to fix linting errors
        run: npx standard --fix

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
